### ISSUE TITLE
missing header info

### ISSUE THREAD

**Issue by jerry3904** [TheNiteCoder/python-fluxbox-keys-merger#1]
Hi NC --

For distribution with MX Linux, we need something like this info at the top:

#<Purpose>
#<author, contact, repo source>
#<license!>

Thanks.

Jerry3904

**Comment by TheNiteCoder** [comment]
Fixed in  [227dbf3](https://github.com/TheNiteCoder/python-fluxbox-keys-merger/commit/227dbf36034e647867403a184d46769ac0e72ecb)
